### ISSUE TITLE
add content

### ISSUE THREAD

**Issue by skymecode** [Tosuke-sama/Forum-Website#2]
can u pull up some contents to your project   from my blog?

**Comment by Tosuke-sama** [comment]
Of course, please leave the address of your blog content

> can u pull up some contents to your project from my blog?

**Comment by skymecode** [comment]
> Of course, please leave the address of your blog content
> 
> > can u pull up some contents to your project from my blog?

https://skym1.gitee.io/%E5%90%8E%E7%AB%AF/%E6%95%B0%E6%8D%AE%E5%BA%93/1.html
